# Generated by Django 5.0.4 on 2024-04-11 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.SmallIntegerField(choices=[(1, 'male'), (2, 'female'), (3, 'other')], null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='government',
            field=models.SmallIntegerField(choices=[(1, 'Ariana'), (2, 'Tunis'), (3, 'Ben Arous')], null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_login_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_login_date_display',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='tel',
            field=models.IntegerField(null=True),
        ),
    ]
