version: '3.8'
services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    ports:
      - "3307:3306"
    networks:
      - microservice
    volumes:
      - mysql_data:/var/lib/mysql
  api-gateway:
    build: ./api-gateway/
    ports:
      - "8088:8088"
    environment:
      eureka.client.serviceUrl.defaultZone: http://discovery-service:8761/eureka
      server.port: 8761
    networks:
      - microservice
    depends_on:
      - mysql
  discovery-service:
    build: ./discovery-server
    container_name: discovery-service
    ports:
      - '8761:8761'
    environment:
      server.port: 8761
    networks:
      - microservice
    depends_on:
      - mysql
  event:
    build: ./microEvent/
    ports:
      - "9093:8080"
    environment:
      spring.datasource.url: "jdbc:mysql://mysql:3306/EventDb?createDatabaseIfNotExist=true"
      eureka.client.serviceUrl.defaultZone: http://discovery-service:8761/eureka
      server.port: 8761
    networks:
      - microservice
  product:
    build: ./microProduct/
    ports:
      - "8070:8070"
    environment:
      spring.datasource.url: "jdbc:mysql://mysql:3306/ProductMicroDb?createDatabaseIfNotExist=true"
      eureka.client.serviceUrl.defaultZone: http://discovery-service:8761/eureka
      server.port: 8761
    networks:
      - microservice
    depends_on:
      - mysql
  reservation:
    build: ./microReservation/
    ports:
      - "9090:9090"
    environment:
      spring.datasource.url: "jdbc:mysql://mysql:3306/ReservationMicroDb?createDatabaseIfNotExist=true"
      eureka.client.serviceUrl.defaultZone: http://discovery-service:8761/eureka
      server.port: 8761
    networks:
      - microservice
    depends_on:
      - mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    environment:
      PMA_HOST: mysql
      PMA_PORT: 8861
      MYSQL_ROOT_PASSWORD: "" # Set according to your MySQL setup
    ports:
      - "8081:80" # Map phpMyAdmin to port 8081 on the host
    networks:
      - microservice

networks:
  microservice:
volumes:
  mysql_data:
